version: "3.9"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-reverse-proxy
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - gateway
    networks:
      - internal

  gateway:
    build:
      context: ./services/gateway
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/gateway:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    networks:
      - internal

  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/user-service:/app
      - /app/node_modules
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=development
    networks:
      - internal

  notes-service:
    build:
      context: ./services/notes-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/notes-service:/app
      - /app/node_modules
    ports:
      - "4002:4002"
    environment:
      - NODE_ENV=development
    networks:
      - internal

networks:
  internal:
    driver: bridge
