name: Terraform Deploy

on:
  workflow_dispatch:
    inputs:
      command:
        description: "Terraform command to run"
        required: true
        default: "plan"
        type: choice
        options:
          - plan
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.4

      - name: Terraform Init
        run: |
          cd hello-world-terraform/infra
          terraform init

      - name: Terraform Plan
        if: github.event.inputs.command == 'plan'
        run: |
          cd hello-world-terraform/infra 
          terraform plan -var-file="terraform.tfvars"
      - name: Terraform Apply
        if: github.event.inputs.command == 'apply'
        run: |
          cd hello-world-terraform/infra 
          terraform apply -input=false -auto-approve -var-file="terraform.tfvars"

      - name: Terraform Destroy
        if: github.event.inputs.command == 'destroy'
        run: |
          cd hello-world-terraform/infra
          terraform destroy -input=false -auto-approve -var-file="terraform.tfvars"

      # - name: Terraform Apply
      #   if: github.event.inputs.command == 'apply'
      #   run: |
      #     cd hello-world-terraform/infra
      #     terraform apply -auto-approve -var-file="terraform.tfvars"

      # - name: Terraform Destroy
      #   if: github.event.inputs.command == 'destroy'
      #   run: |
      #     cd hello-world-terraform/infra
      #     terraform destroy -auto-approve -var-file="terraform.tfvars"
